export const COLORS = {
  primary: "#1a3c6e",
  primaryDark: "#122a50",
  primaryLight: "#2255a0",
  accent: "#c8a84b",
  accentLight: "#f0d080",
  white: "#ffffff",
  offWhite: "#f5f7fa",
  lightGray: "#eef1f6",
  text: "#1a1a2e",
  textMuted: "#5a6a85",
  border: "#dde3ef",
  success: "#1a7a4a",
  successBg: "#e8f5ee",
  warning: "#c07a10",
  warningBg: "#fdf3e0",
  danger: "#a32020",
  dangerBg: "#fdeaea",
};

export const styles = {
  "@global": `
    @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600&family=Source+Sans+3:wght@300;400;500;600&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Source Sans 3', sans-serif; background: #f0f2f7; color: #1a1a2e; }
    a { text-decoration: none; color: inherit; }
  `,
};

export const S = {
  topBar: {
    background: COLORS.primaryDark,
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    padding: "6px 2rem",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    letterSpacing: 0.3,
  },
  navbar: {
    background: COLORS.primary,
    boxShadow: "0 2px 12px rgba(0,0,0,0.18)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  navInner: {
    maxWidth: 1160,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    padding: "0 2rem",
    gap: 0,
  },
  navLogo: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "12px 0",
    marginRight: "auto",
    textDecoration: "none",
  },
  logoCircle: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: COLORS.white,
    border: `3px solid ${COLORS.accent}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  logoText: {
    color: COLORS.white,
    lineHeight: 1.25,
  },
  navLink: (active) => ({
    color: active ? COLORS.accent : "rgba(255,255,255,0.85)",
    padding: "18px 15px",
    fontSize: 13.5,
    fontWeight: active ? 600 : 400,
    fontFamily: "'Source Sans 3', sans-serif",
    cursor: "pointer",
    border: "none",
    background: "none",
    borderBottom: `3px solid ${active ? COLORS.accent : "transparent"}`,
    transition: "all 0.18s",
    whiteSpace: "nowrap",
  }),
  hero: {
    background: `linear-gradient(135deg, ${COLORS.primaryDark} 0%, ${COLORS.primary} 50%, #1e4d8c 100%)`,
    padding: "3.5rem 2rem",
    color: COLORS.white,
    position: "relative",
    overflow: "hidden",
  },
  heroInner: {
    maxWidth: 1160,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: "3rem",
    position: "relative",
    zIndex: 1,
  },
  heroBadge: {
    display: "inline-block",
    background: "rgba(200,168,75,0.2)",
    border: `1px solid ${COLORS.accent}`,
    color: COLORS.accentLight,
    fontSize: 11,
    letterSpacing: 1.5,
    padding: "4px 12px",
    borderRadius: 2,
    marginBottom: 12,
    textTransform: "uppercase",
    fontWeight: 600,
  },
  heroTitle: {
    fontFamily: "'EB Garamond', serif",
    fontSize: 36,
    fontWeight: 600,
    lineHeight: 1.2,
    marginBottom: 8,
  },
  heroSub: {
    fontSize: 14,
    opacity: 0.8,
    marginBottom: 24,
    maxWidth: 480,
    lineHeight: 1.7,
  },
  card: (hovering) => ({
    background: COLORS.white,
    borderRadius: 8,
    border: `1px solid ${hovering ? COLORS.primaryLight : COLORS.border}`,
    padding: "1.5rem",
    transition: "all 0.2s",
    boxShadow: hovering ? "0 8px 24px rgba(26,60,110,0.13)" : "0 2px 8px rgba(0,0,0,0.05)",
    transform: hovering ? "translateY(-3px)" : "none",
    cursor: "pointer",
  }),
  section: {
    maxWidth: 1160,
    margin: "0 auto",
    padding: "2.5rem 2rem",
  },
  sectionTitle: {
    fontFamily: "'EB Garamond', serif",
    fontSize: 26,
    fontWeight: 600,
    color: COLORS.primary,
    marginBottom: 4,
    borderBottom: `3px solid ${COLORS.accent}`,
    paddingBottom: 8,
    display: "inline-block",
  },
  btn: (variant = "primary") => ({
    padding: "9px 22px",
    borderRadius: 4,
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "'Source Sans 3', sans-serif",
    cursor: "pointer",
    border: variant === "primary" ? "none" : `1.5px solid ${COLORS.primary}`,
    background: variant === "primary" ? COLORS.primary : "transparent",
    color: variant === "primary" ? COLORS.white : COLORS.primary,
    transition: "all 0.18s",
    letterSpacing: 0.3,
  }),
  input: {
    width: "100%",
    padding: "9px 12px",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 4,
    fontSize: 14,
    fontFamily: "'Source Sans 3', sans-serif",
    color: COLORS.text,
    background: COLORS.white,
    outline: "none",
    transition: "border 0.18s",
  },
  label: {
    display: "block",
    fontSize: 13,
    color: COLORS.textMuted,
    marginBottom: 4,
    fontWeight: 500,
  },
  formGroup: { marginBottom: "1rem" },
  stepPill: (state) => ({
    padding: "6px 16px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    cursor: "default",
    border: "1.5px solid",
    borderColor: state === "active" ? COLORS.primary : state === "done" ? COLORS.success : COLORS.border,
    background: state === "active" ? COLORS.primary : state === "done" ? COLORS.successBg : "transparent",
    color: state === "active" ? COLORS.white : state === "done" ? COLORS.success : COLORS.textMuted,
  }),
  infoBox: {
    background: "#eaf2fb",
    borderLeft: `4px solid ${COLORS.primary}`,
    borderRadius: "0 6px 6px 0",
    padding: "10px 14px",
    fontSize: 13,
    color: COLORS.primaryDark,
    marginBottom: "1rem",
    lineHeight: 1.6,
  },
  fileUpload: {
    border: `2px dashed ${COLORS.border}`,
    borderRadius: 6,
    padding: "1rem",
    textAlign: "center",
    fontSize: 13,
    color: COLORS.textMuted,
    cursor: "pointer",
    transition: "border 0.18s",
  },
  badge: (type) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600,
    background: type === "success" ? COLORS.successBg : type === "pending" ? COLORS.warningBg : COLORS.dangerBg,
    color: type === "success" ? COLORS.success : type === "pending" ? COLORS.warning : COLORS.danger,
  }),
  footer: {
    background: COLORS.primaryDark,
    color: "rgba(255,255,255,0.8)",
    padding: "2.5rem 2rem 1rem",
  },
  footerInner: {
    maxWidth: 1160,
    margin: "0 auto",
  },
  ticker: {
    background: COLORS.accent,
    color: COLORS.primaryDark,
    padding: "7px 2rem",
    fontSize: 13,
    fontWeight: 600,
    display: "flex",
    gap: 12,
    alignItems: "center",
    overflow: "hidden",
  },
};